image: "gableroux/unity3d:2018.4.12f1-android"

stages:
- test
- build
- deploy

variables:
  BUILD_NAME: BrainVisualizer
  UNITY_ACTIVATION_FILE: ./unity3d.alf

.unity_before_script: &unity_before_script
  before_script:
  - chmod +x ./ci/before_script.sh && ./ci/before_script.sh

.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - Library/

.test_conversion: &test_conversion
  - java -classpath ./ci Stylizer ./ci/nunit3-junit.xslt $(pwd)/$TEST_PLATFORM-results.xml $(pwd)/$TEST_PLATFORM-results-converted.xml

get-activation-file:
  when: manual
  stage: .pre
  script:
    - chmod +x ./ci/get_activation_file.sh && ./ci/get_activation_file.sh
  artifacts:
    paths:
      - $UNITY_ACTIVATION_FILE
    expire_in: 10 min
  only:
  - master

.test: &test
  stage: test
  <<: *unity_before_script
  <<: *cache
  script:
  - chmod +x ./ci/test.sh && ./ci/test.sh
  after_script:
    - *test_conversion
  artifacts:
    paths:
    - $(pwd)/$TEST_PLATFORM-results-converted.xml
    reports:
      junit: $(pwd)/$TEST_PLATFORM-results-converted.xml
  only:
  - merge_request

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

test-playmode:
  <<: *test
  variables:
    TEST_PLATFORM: playmode

.build: &build
  stage: build
  #tip: you can reuse same stage to do everything in parallel and reduce overall time
  # stage: test
  <<: *unity_before_script
  <<: *cache
  script:
  - chmod +x ./ci/build.sh && ./ci/build.sh
  artifacts:
    paths:
    - ./Builds/
  only:
  - Quest-Build
  - Go-Build

build-android:
  <<: *build
  image: gableroux/unity3d:2018.4.12f1-android
  variables:
    BUILD_TARGET: Android