# This is a basic workflow to help you get started with Actions

name: CI
env:
  BUILD_NAME: BrainViz
  TARGET_PLATFORM: Android
  UNITY_VERSION: 2019.2.21f1
  PROJECT_PATH: BrainVisualizer
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  activation:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: $UNITY_VERSION
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  # Runs the Unity's Testing Suite
  test:
    name: Run Unity Testing Suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playMode
          - editMode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          key: Library
      - name: Unity - Test
        id: testProject
        uses: webbertaken/unity-test-runner@v1.5
        with: 
          unityVersion: $UNITY_VERSION
      - name: Upload Test Results
        uses: actions/upload-artifacts@v1
        with:
          name: $BUILD_NAME_${{ matrix.testMode }}_results
          path: ${{ steps.testProject.output.artifactsPath }}
        
  # Builds the Unity Project
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: actions/cache@v1.1.0
      with:
        path: $PROJECT_PATH/Library
        key: Library-$PROJECT_PATH-$TARGET_PLATFORM
        restore-keys: |
          Library-$PROJECT_PATH-
          Library-
    - name: Unity - Build
      uses: webbertakken/unity-builder@v0.11
      with:
        unityVersion: $UNITY_VERSION
        targetPlatform: $TARGET_PLATFORM
        buildName: $BUILD_NAME
        buildsPath: $PROJECT_PATH/build/android
        buildMethod: BuildCommand.PerformBuild
    - uses: actions/upload-artifacts@v1
      with:
        name: $BUILD_NAME
        path: $PROJECT_PATH/build/android 
        
